create extension if not exists "uuid-ossp";

create table if not exists "LoginUser" (
  id uuid primary key,
  created_date timestamptz not null,
  updated_date timestamptz not null,
  email varchar(255) not null unique,
  full_name varchar(255) not null,
  password_hash varchar(255) not null,
  status varchar(50) not null,
  role varchar(50) not null,
  is_email_verified boolean not null,
  partner_id uuid null,
  last_login_at timestamptz null
);

create table if not exists "Partner" (
  id uuid primary key,
  created_date timestamptz not null,
  updated_date timestamptz not null,
  user_id uuid null,
  email varchar(255) not null unique,
  created_by varchar(255) null,
  full_name varchar(255) not null,
  display_name varchar(120) null,
  cpf varchar(50) null,
  phone varchar(50) null,
  birth_date date null,
  gender varchar(50) null,
  status varchar(50) not null,
  graduation varchar(50) not null,
  graduation_start_date date null,
  first_purchase_done boolean not null,
  total_bonus_generated numeric(18,2) not null default 0,
  bonus_for_withdrawal numeric(18,2) not null default 0,
  bonus_for_purchases numeric(18,2) not null default 0,
  total_withdrawn numeric(18,2) not null default 0,
  total_spent_purchases numeric(18,2) not null default 0,
  groups_formed int not null default 0,
  unique_code varchar(50) null unique,
  accepted_terms boolean not null default false,
  accepted_rules boolean not null default false,
  email_verified boolean not null default false,
  phone_verified boolean not null default false,
  notification_email boolean not null default true,
  notification_sms boolean not null default false,
  notification_whatsapp boolean not null default false,
  notification_frequency varchar(50) null,
  referrer_id uuid null,
  referrer_name varchar(255) null,
  pending_reasons jsonb not null default '[]'::jsonb,
  pix_key varchar(120) null,
  address_street varchar(255) null,
  address_number varchar(50) null,
  address_complement varchar(255) null,
  address_neighborhood varchar(255) null,
  address_city varchar(100) null,
  address_state varchar(10) null,
  address_cep varchar(20) null,
  email_change_code varchar(50) null,
  email_change_new varchar(255) null,
  email_change_expiry timestamptz null
);
